title: "Moochan Daniel Lee"
subtitle: "Equity Research Portfolio"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
paginate: 5
locale: "en-US"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "Moochan Daniel Lee"
  avatar : "/assets/images/headshot.jpg" # You'll need to upload this
  bio    : "Aspiring Equity Research Analyst"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/moochan-lee/"
