title: "Moochan's homepage"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
paginate: 5
locale: "en-US"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
